export const formConfigs = {
  "afc-preventive-maintenance-monthly-tvm": {
    title: "AFC PREVENTIVE MAINTENANCE CHECKLIST (Monthly)",
    formType: "afc-preventive-maintenance-monthly-tvm",
    headerFields: [
      { key: "title", label: "", colSpan: 45, value: "AFC PREVENTIVE MAINTENANCE CHECKLIST (Monthly)" },
      { key: "station", label: "Station Name", colSpan: 8 },
      { key: "frequency", label: "FREQUENCY", colSpan: 12, value: "Monthly" },
      { key: "month", label: "Month", colSpan: 8 },
      { key: "date", label: "DATE", colSpan: 11 },
    ],
    activities1: {
      label: "TVM",
      key: "activities",
      reference: "Ref: O&M/TELE-AFC/SOP/01",
      columns: [
        { key: "TVM1", label: "TVM", colSpan: 2 },
        { key: "TVM2", label: "TVM", colSpan: 2 },
        { key: "TVM3", label: "TVM", colSpan: 2 },
        { key: "TVM4", label: "TVM", colSpan: 2 },
        { key: "TVM5", label: "TVM", colSpan: 2 },
      ],
      remarkKey: "remark",
      actionKey: "action",
      deficiencyKey: "deficiency",
      rows: [
        { srNo: 1, activity: "Visual Inspection", description: "Check Fixing & Alignment of all modules of TVM" },
        { srNo: 2, activity: "Visual Inspection", description: "Checking Silicon sealing of TVM Cabinet" },
        { srNo: 3, activity: "Visual Inspection", description: "Checking Silicon sealing of TVM Cabinet" },
        { srNo: 4, activity: "Visual Inspection", description: "Checking of any opening inside TVM cabinet" },
        { srNo: 5, activity: "Visual Inspection", description: "Checking of Power Supply and Battery" },
        { srNo: 6, activity: "Visual Inspection", description: "Check Station ID" },
        { srNo: 7, activity: "Visual Inspection", description: "Check Device ID" },
        { srNo: 8, activity: "Visual Inspection", description: "Check Date and Time" },
        { srNo: 9, activity: "Visual Inspection", description: "Check Passenger Information Display (PID)" },
        { srNo: 10, activity: "Cleaning", description: "Cleaning of all modules of TVM" },
        { srNo: 11, activity: "Cleaning", description: "Cleaning of lexan covering board of display" },
        { srNo: 12, activity: "Cleaning", description: "Cleaning of Coin hopper opto sensor" },
        { srNo: 13, activity: "Cleaning", description: "Cleaning of Cooling fans" },
        { srNo: 14, activity: "Cleaning", description: "Checking and Cleaning of Cooling fan filter" },
        { srNo: 15, activity: "Cleaning", description: "Cleaning of BNR" },
        { srNo: 16, activity: "Cleaning", description: "Cleaning of Bank card reader" },
        { srNo: 17, activity: "Module Test (Maintenance Menu)", description: "Check LAN Status (Ping Server)" },
        { srNo: 18, activity: "Module Test (Maintenance Menu)", description: "Component Status" },
        { srNo: 19, activity: "Module Test (Maintenance Menu)", description: "Token Dispenser Test" },
        { srNo: 20, activity: "Module Test (Maintenance Menu)", description: "Bank Note system Test" },
        { srNo: 21, activity: "Module Test (Maintenance Menu)", description: "Payment Terminal Test" },
        { srNo: 22, activity: "Module Test (Maintenance Menu)", description: "Printer Test" },
        { srNo: 23, activity: "Module Test (Maintenance Menu)", description: "Audio Test" },
        { srNo: 24, activity: "Module Test (Maintenance Menu)", description: "Bowl LED Test" },
        { srNo: 25, activity: "Module Test (Maintenance Menu)", description: "Alarm Test" },
        { srNo: 26, activity: "Module Test (Maintenance Menu)", description: "Coin Dispenser Test" },
        { srNo: 27, activity: "Module Test (Maintenance Menu)", description: "Card Reader Test" },
      ],
    },
    activities2: null,
    activities3: null,
    staffFields: [
      { nameKey: "staff1_name", desgKey: "staff1_desg", signKey: "staff1_sign", nameColSpan: 25, desgColSpan: 5, signColSpan: 5 },
      { nameKey: "staff2_name", desgKey: "staff2_desg", signKey: "staff2_sign", nameColSpan: 25, desgColSpan: 5, signColSpan: 5 },
      { nameKey: "staff3_name", desgKey: "staff3_desg", signKey: "staff3_sign", nameColSpan: 25, desgColSpan: 5, signColSpan: 5 },
    ],
    editPath: "/edit/afc-preventive-monthly-tvm",
  },
  "afc-preventive-maintenance-monthly-tom-ec": {
    title: "AFC PREVENTIVE MAINTENANCE CHECKLIST (MONTHLY)",
    formType: "afc-preventive-maintenance-monthly-tom-ec",
    headerFields: [
      { key: "title", label: "", colSpan: 20, value: "AFC PREVENTIVE MAINTENANCE CHECKLIST (MONTHLY)" },
      { key: "station", label: "Station Name", colSpan: 2 },
      { key: "device_name", label: "Device", colSpan: 2 },
      { key: "date", label: "DATE", colSpan: 7 },
      { key: "month", label: "MONTH", colSpan: 8 },
    ],
    activities1: {
      label: "TOM",
      key: "activities1",
      reference: "Ref: O&M/TELE-AFC/SOP/01",
      columns: [
        { key: "TOM1", label: "TOM" },
        { key: "TOM2", label: "TOM" },
        { key: "TOM3", label: "TOM" },
        { key: "TOM4", label: "TOM" },
        { key: "TOM5", label: "TOM" },
      ],
      remarkKey: "remark",
      actionKey: "action",
      deficiencyKey: "deficiency",
      rows: [
        { srNo: 1, activity: "Visual Inspection", description: "Check Fixing & Alignment of all modules of TOM" },
        { srNo: 2, activity: "Visual Inspection", description: "Checking of all Cable connection and dressing" },
        { srNo: 3, activity: "Visual Inspection", description: "Check Date and Time" },
        { srNo: 4, activity: "Visual Inspection", description: "Check Lubrication of all locks with silicone oil" },
        { srNo: 5, activity: "Visual Inspection", description: "Sealing of unused USB Port" },
        { srNo: 6, activity: "Visual Inspection", description: "Check TOM should be logged in via login card only" },
        { srNo: 7, activity: "Visual Inspection", description: "Check for disabled USB drives" },
        { srNo: 8, activity: "Cleaning", description: "Cleaning of Opto sensor, Antenna, Token tray, Reject bin, Token box, token path, token hopper" },
        { srNo: 9, activity: "Cleaning", description: "Cleaning of all modules of TOM" },
        { srNo: 10, activity: "Cleaning", description: "Cleaning of Trench" },
        { srNo: 11, activity: "Module Test (Maintenance Menu)", description: "Card Reader Writer (CRW) Test" },
        { srNo: 12, activity: "Module Test (Maintenance Menu)", description: "Printer Test" },
        { srNo: 13, activity: "Module Test (Maintenance Menu)", description: "Passenger Display Unit (PDU) Test" },
        { srNo: 14, activity: "Module Test (Maintenance Menu)", description: "Token Dispensing Machine (TDM) Test" },
        { srNo: 15, activity: "Module Test (Maintenance Menu)", description: "Touch Screen Test" },
        { srNo: 16, activity: "Module Test (Maintenance Menu)", description: "Counter Communication System Test" },
        { srNo: 17, activity: "Module Test (Maintenance Menu)", description: "Keyboard, Mouse Test" },
        { srNo: 18, activity: "Module Test (Maintenance Menu)", description: "Check LAN Status" },
        { srNo: 19, activity: "Module Test (Maintenance Menu)", description: "Check Power strip" },
      ],
    },
    activities2: {
      label: "EC",
      key: "activities1",
      startIndex: 19,
      reference: "Ref: O&M/TELE-AFC/SOP/01",
      columns: [
        { key: "TOM1", label: "SCR-EC" },
        { key: "TOM2", label: "TOM-EC" },
        { key: "TOM3", label: "TOM-EC" },
        { key: "TOM4", label: "TOM-EC" },
        { key: "TOM5", label: "TOM-EC" },
      ],
      remarkKey: "remark",
      actionKey: "action",
      deficiencyKey: "deficiency",
      rows: [
        { srNo: 1, activity: "Visual Inspection", description: "Checking of all Cable connection and dressing" },
        { srNo: 2, activity: "Visual Inspection", description: "Tightening of all Electrical Connection in EC" },
        { srNo: 3, activity: "Visual Inspection", description: "Checking of all indicators" },
        { srNo: 4, activity: "Cleaning", description: "Cleaning of Electrical Cabinet" },
        { srNo: 5, activity: "Module Test", description: "ELCB Push Button Operation" },
      ],
    },
    activities3: null,
    staffFields: [
      { nameKey: "staff1_name", desgKey: "staff1_desg", signKey: "staff1_sign", nameColSpan: 10, desgColSpan: 5, signColSpan: 5 },
      { nameKey: "staff2_name", desgKey: "staff2_desg", signKey: "staff2_sign", nameColSpan: 10, desgColSpan: 5, signColSpan: 5 },
      { nameKey: "staff3_name", desgKey: "staff3_desg", signKey: "staff3_sign", nameColSpan: 10, desgColSpan: 5, signColSpan: 5 },
    ],
    editPath: "/edit/pmlog-maintain-monthly",
  },
  "afc-preventive-maintenance-monthly-annexure-a": {
    title: "AFC PREVENTIVE MAINTENANCE CHECKLIST (MONTHLY) (ANNEXURE-A)",
    formType: "afc-preventive-maintenance-monthly-annexure-a",
    headerFields: [
      { key: "title", label: "", colSpan: 11, value: "AFC PREVENTIVE MAINTENANCE CHECKLIST (MONTHLY) (ANNEXURE-A)" },
      { key: "document", label: "", colSpan: 2, value: "Document: O&M/AFC/LINE/CH01" },
      { key: "station", label: "STN. NAME", colSpan: 3 },
      { key: "frequency", label: "FREQUENCY", colSpan: 1, value: "MONTHLY" },
      { key: "date", label: "DATE", colSpan: 6 },
      { key: "month", label: "MONTH", colSpan: 3 },
    ],
    activities1: {
      label: "SC",
      key: "activities1",
      reference: "Ref: O&M/TELE-AFC/SOP/01",
      columns: [
        { key: "SC1", label: "SC" },
        { key: "SC2", label: "SC" },
        { key: "SC3", label: "SC" },
        { key: "SC4", label: "SC" },
        { key: "SC5", label: "SC" },
        { key: "SC6", label: "SC" },
      ],
      remarkKey: "remark",
      actionKey: "action",
      deficiencyKey: "deficiency",
      rows: [
        { srNo: 1, activity: "Visual Inspection", description: "Check Fixing & Alignment of all modules of SC" },
        { srNo: 2, activity: "Visual Inspection", description: "Checking of all Cable connection and dressing" },
        { srNo: 3, activity: "Visual Inspection", description: "Check Date and Time" },
        { srNo: 4, activity: "Visual Inspection", description: "Sealing of unused USB Port" },
        { srNo: 5, activity: "Visual Inspection", description: "Check for disabled USB Drives" },
        { srNo: 6, activity: "Cleaning", description: "External cleaning of all modules of SC" },
        { srNo: 7, activity: "Cleaning", description: "Check working of redundant power supply of SC server" },
        { srNo: 8, activity: "Cleaning", description: "Test different modes in device manager by applying and releasing on equipments" },
      ],
    },
    activities2: {
      label: "AVM",
      key: "activities2",
      reference: "Ref: O&M/TELE-AFC/SOP/01",
      columns: [
        { key: "avm1", label: "AVM" },
        { key: "avm2", label: "AVM" },
        { key: "avm3", label: "AVM" },
        { key: "avm4", label: "AVM" },
        { key: "avm5", label: "AVM" },
        { key: "avm6", label: "AVM" },
      ],
      remarkKey: "remarkavm",
      actionKey: "actionavm",
      deficiencyKey: "deficiencyavm",
      rows: [
        { srNo: 1, activity: "Visual Inspection", description: "Check the serviceability of AVM" },
        { srNo: 2, activity: "Visual Inspection", description: "Checking of all Cable connection and dressing" },
        { srNo: 3, activity: "Visual Inspection", description: "Check Date and Time" },
        { srNo: 4, activity: "Visual Inspection", description: "Check Station ID" },
        { srNo: 5, activity: "Visual Inspection", description: "Check Device ID" },
        { srNo: 6, activity: "Visual Inspection", description: "Check Lubrication of all locks with silicone oil" },
        { srNo: 7, activity: "Module Test (Maintenance Menu)", description: "Card Reader Test" },
        { srNo: 8, activity: "Module Test (Maintenance Menu)", description: "Passenger Information Display (PID) Test" },
        { srNo: 9, activity: "Module Test (Maintenance Menu)", description: "Check LAN Status (Ping Server)" },
      ],
    },
    activities3: {
      label: "SWITCH",
      key: "activities3",
      reference: "Ref: O&M/TELE-AFC/SOP/01",
      columns: [
        { key: "swt1", label: "SWT" },
        { key: "swt2", label: "SWT" },
        { key: "swt3", label: "SWT" },
        { key: "swt4", label: "SWT" },
        { key: "swt5", label: "SWT" },
        { key: "swt6", label: "SWT" },
      ],
      remarkKey: "remarkswt",
      actionKey: "actionswt",
      deficiencyKey: "deficiencyswt",
      rows: [
        { srNo: 1, activity: "Visual Inspection", description: "Check Fixing & Alignment of all modules of Switch Rack" },
        { srNo: 2, activity: "Visual Inspection", description: "Checking of all Cable connection and dressing" },
        { srNo: 3, activity: "Visual Inspection", description: "Check internal fan status of Switches" },
        { srNo: 4, activity: "Cleaning", description: "Cleaning of Switch Rack and its fan" },
        { srNo: 5, activity: "Cleaning", description: "External cleaning of Switch" },
        { srNo: 6, activity: "Module Test", description: "Test of redundant link" },
        { srNo: 7, activity: "Module Test", description: "Check if Switches are working normal and all equipments are on LAN" },
      ],
    },
    staffFields: [
      { nameKey: "staff1_name", desgKey: "staff1_desg", colSpan: 3 },
      { nameKey: "staff2_name", desgKey: "staff2_desg", colSpan: 3 },
      { nameKey: "staff3_name", desgKey: "staff3_desg", colSpan: 3 },
    ],
    editPath: "/edit/afc-preventive-monthly-annexure-a",
  },
  "afc-preventive-maintenance-tom-half-yearly": {
    title: "AFC PREVENTIVE MAINTENANCE CHECKLIST (TOM HALF YEARLY) (ANNEXURE-B)",
    formType: "afc-preventive-maintenance-tom-half-yearly",
    headerFields: [
      { key: "station", label: "STN. NAME", colSpan: 2 },
      { key: "", label: "", colSpan: 1 },
      { key: "date", label: "DATE", colSpan: 4 },
      { key: "month", label: "MONTH", colSpan: 3 },
      { key: "", label: "", colSpan: 1 },
      { key: "department", label: "DEPARTMENT", colSpan: 2 },
    ],
    activities1: {
      label: "TOM",
      key: "activities1",
      reference: "Ref: O&M/TELE-AFC/SOP/01",
      columns: [
        { key: "TOM1", label: "1" },
        { key: "TOM2", label: "2" },
        { key: "TOM3", label: "3" },
        { key: "TOM4", label: "4" },
        { key: "TOM5", label: "5" },
        { key: "TOM6", label: "6" },
        { key: "TOM7", label: "7" },
      ],
      remarkKey: "remark",
      actionKey: "action",
      deficiencyKey: "deficiency",
      rows: [
        { srNo: 1, activity: "Visual Inspection", description: "Check Fixing & Alignment of all modules of TOM" },
        { srNo: 2, activity: "Visual Inspection", description: "Checking of all Cable connection and dressing" },
        { srNo: 3, activity: "Visual Inspection", description: "Check Date and Time" },
        { srNo: 4, activity: "Visual Inspection", description: "Check Lubrication of all locks with silicone oil" },
        { srNo: 5, activity: "Visual Inspection", description: "Sealing of unused USB Port" },
        { srNo: 6, activity: "Visual Inspection", description: "Check TOM should be logged in via login card only" },
        { srNo: 7, activity: "Visual Inspection", description: "Check for disabled USB drives" },
        { srNo: 8, activity: "Cleaning", description: "Cleaning of Opto sensor, Antenna, Token tray, Reject bin, Token box, token path, token hopper" },
        { srNo: 9, activity: "Cleaning", description: "Cleaning of Trench" },
        { srNo: 10, activity: "Module Test", description: "Card Reader Writer (CRW) Test" },
        { srNo: 11, activity: "Module Test", description: "Printer Test" },
        { srNo: 12, activity: "Module Test", description: "Passenger Display Unit (PDU) Test" },
        { srNo: 13, activity: "Module Test", description: "Token Dispensing Machine (TDM) Test" },
        { srNo: 14, activity: "Module Test", description: "Touch Screen Test" },
        { srNo: 15, activity: "Module Test", description: "Counter Communication System Test" },
        { srNo: 16, activity: "Module Test", description: "Keyboard, Mouse Test" },
      ],
    },
    activities2: {
      label: "EC",
      key: "activities2",
      reference: "Ref: O&M/TELE-AFC/SOP/01",
      columns: [
        { key: "EC1", label: "1" },
        { key: "EC2", label: "2" },
        { key: "EC3", label: "3" },
        { key: "EC4", label: "4" },
        { key: "EC5", label: "5" },
        { key: "EC6", label: "6" },
        { key: "EC7", label: "7" },
      ],
      remarkKey: "remarks",
      actionKey: "actions",
      deficiencyKey: "deficiency1",
      rows: [
        { srNo: 1, activity: "Visual Inspection", description: "Checking of all Cable connection and dressing" },
        { srNo: 2, activity: "Visual Inspection", description: "Tightening of all Electrical Connection in EC" },
        { srNo: 3, activity: "Visual Inspection", description: "Checking of all indicators" },
        { srNo: 4, activity: "Cleaning", description: "Cleaning of Isolator and all Electrical Cabinet" },
        { srNo: 5, activity: "Module Test", description: "ELCB Push Button Operation" },
        { srNo: 6, activity: "Module Test", description: "Testing of Isolator Mode selector" },
      ],
    },
    activities3: null,
    staffFields: [
      { nameKey: "staff1_name", desgKey: "staff1_desg", colSpan: 3 },
      { nameKey: "staff2_name", desgKey: "staff2_desg", colSpan: 3 },
      { nameKey: "staff3_name", desgKey: "staff3_desg", colSpan: 3 },
    ],
    editPath: "/edit/pm-logbook-half-yearly-tom-mainline",
  },
  "afc-preventive-maintenance-half-yearly-annexure-b": {
    title: "AFC PREVENTIVE MAINTENANCE CHECKLIST (HALF YEARLY) (ANNEXURE-B)",
    formType: "afc-preventive-maintenance-half-yearly-annexure-b",
    headerFields: [
      { key: "title", label: "", colSpan: 11, value: "AFC PREVENTIVE MAINTENANCE CHECKLIST (HALF YEARLY) (ANNEXURE-B)" },
      { key: "document", label: "", colSpan: 2, value: "Document: O&M/AFC/LINE/CH02" },
      { key: "stn_name", label: "STN. NAME", colSpan: 3 },
      { key: "frequency", label: "FREQUENCY", colSpan: 1, value: "HALF YEARLY" },
      { key: "date", label: "DATE", colSpan: 6 },
      { key: "month", label: "MONTH", colSpan: 3 },
    ],
    activities1: {
      label: "SC",
      key: "activities1",
      reference: "Ref: O&M/TELE-AFC/SOP/01",
      columns: [
        { key: "SC1", label: "SC" },
        { key: "SC2", label: "SC" },
        { key: "SC3", label: "SC" },
        { key: "SC4", label: "SC" },
        { key: "SC5", label: "SC" },
        { key: "SC6", label: "SC" },
      ],
      remarkKey: "remark",
      actionKey: "action",
      deficiencyKey: "deficiency",
      rows: [
        { srNo: 1, activity: "Visual Inspection", description: "Check Fixing & Alignment of all modules of SC" },
        { srNo: 2, activity: "Visual Inspection", description: "Checking of all Cable connection and dressing" },
        { srNo: 3, activity: "Visual Inspection", description: "Check Date and Time" },
        { srNo: 4, activity: "Visual Inspection", description: "Sealing of unused USB Port" },
        { srNo: 5, activity: "Visual Inspection", description: "Check for disabled USB Drives" },
        { srNo: 6, activity: "Cleaning", description: "Cleaning and checking of sub modules of SC (Printer, Keyboard and Mouse etc)" },
        { srNo: 7, activity: "Cleaning", description: "Cleaning of SC Server (interior & exterior)" },
        { srNo: 8, activity: "Cleaning", description: "Cleaning of SC HDD and check their proper fitment" },
        { srNo: 9, activity: "Testing", description: "Test different modes in device manager by applying and releasing on equipments" },
        { srNo: 10, activity: "Testing", description: "Check working of redundant power supply of SC server" },
      ],
    },
    activities2: {
      label: "AVM",
      key: "activities2",
      reference: "Ref: O&M/TELE-AFC/SOP/01",
      columns: [
        { key: "avm1", label: "AVM" },
        { key: "avm2", label: "AVM" },
        { key: "avm3", label: "AVM" },
        { key: "avm4", label: "AVM" },
        { key: "avm5", label: "AVM" },
        { key: "avm6", label: "AVM" },
      ],
      remarkKey: "remarkavm",
      actionKey: "actionavm",
      deficiencyKey: "deficiencyavm",
      rows: [
        { srNo: 1, activity: "Visual Inspection", description: "Check the serviceability of AVM" },
        { srNo: 2, activity: "Visual Inspection", description: "Checking of all Cable connection and dressing" },
        { srNo: 3, activity: "Visual Inspection", description: "Check Date and Time" },
        { srNo: 4, activity: "Visual Inspection", description: "Check Station ID" },
        { srNo: 5, activity: "Visual Inspection", description: "Check Device ID" },
        { srNo: 6, activity: "Visual Inspection", description: "Check Lubrication of all locks with silicone oil" },
        { srNo: 7, activity: "Module Testing", description: "Card Reader Test" },
        { srNo: 8, activity: "Testing", description: "Passenger Information Display (PID) Test" },
        { srNo: 9, activity: "Testing", description: "Check LAN Status (Ping Server)" },
      ],
    },
    activities3: {
      label: "SWITCH",
      key: "activities3",
      reference: "Ref: O&M/TELE-AFC/SOP/01",
      columns: [
        { key: "swt1", label: "SWT" },
        { key: "swt2", label: "SWT" },
        { key: "swt3", label: "SWT" },
        { key: "swt4", label: "SWT" },
        { key: "swt5", label: "SWT" },
        { key: "swt6", label: "SWT" },
      ],
      remarkKey: "remarkswt",
      actionKey: "actionswt",
      deficiencyKey: "deficiencyswt",
      rows: [
        { srNo: 1, activity: "Visual Inspection", description: "Check Fixing & Alignment of all modules of Switch Rack" },
        { srNo: 2, activity: "Visual Inspection", description: "Checking of all Cable connection and dressing" },
        { srNo: 3, activity: "Visual Inspection", description: "Check internal fan status of Switches" },
        { srNo: 4, activity: "Cleaning", description: "Cleaning of Switch Rack and its fan" },
        { srNo: 5, activity: "Cleaning", description: "External cleaning of Switch" },
        { srNo: 6, activity: "Module Test", description: "Test of redundant link" },
        { srNo: 7, activity: "Module Test", description: "Check if Switches are working normal and all equipments are on LAN" },
      ],
    },
    staffFields: [
      { nameKey: "staff1_name", desgKey: "staff1_desg", colSpan: 3 },
      { nameKey: "staff2_name", desgKey: "staff2_desg", colSpan: 3 },
      { nameKey: "staff3_name", desgKey: "staff3_desg", colSpan: 3 },
    ],
    editPath: "/edit/afc-pre-annexure-b",
  },
};